[MAcOS]Fix bugs related to height properties
webex/AdaptiveCards pull request #312
Opened 2022-11-28 03:24 UTC by mukuagar

## Description

* Fix issue where elements would not get proper spacing when they were initially hidden and then toggled visible
* Fix issue where container would take spacing even when it was completely empty and had no elements
* Fix issue where input label and error messages were hidden but were still increasing height of card

## Sample Card
Case 1
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "actions": [
        {
            "title": "OK",
            "type": "Action.Submit"
        }
    ],
    "body": [
        {
            "errorMessage": "error message error message error message error message ",
            "height": "stretch",
            "id": "1",
            "isRequired": true,
            "label": "Hello this is label",
            "type": "Input.Date",
            "isVisible": false
        },
        {
            "errorMessage": "error message error message error message error message ",
            "height": "stretch",
            "id": "3",
            "isRequired": true,
            "label": "This is label",
            "type": "Input.Text",
            "isVisible": false
        },
        {
            "actions": [
                {
                    "targetElements": [
                        "1",
                        "3"
                    ],
                    "title": "Action.ToggleVisibility",
                    "type": "Action.ToggleVisibility"
                }
            ],
            "id": "2",
            "type": "ActionSet"
        }
    ],
    "minHeight": "400px",
    "type": "AdaptiveCard",
    "version": "1.3"
}`

Case 2:
`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "minHeight": "300px",
    "body": [
        {
            "type": "Container",
            "style": "accent",
            "minHeight": "200px",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "width": "stretch",
                            "style": "emphasis"
                        },
                        {
                            "type": "Column",
                            "width": "stretch",
                            "style": "good"
                        }
                    ]
                },
                {
                    "type": "Container",
                    "style": "attention"
                },
                {
                    "type": "TextBlock",
                    "wrap": true,
                    "text": "Test Text box"
                }
            ]
        },
        {
            "type": "Container"
        },
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "Test Text box"
        }
    ]
}
`

Case 3:
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "actions": [
        {
            "title": "OK",
            "type": "Action.Submit"
        }
    ],
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "errorMessage": "error message error message error message error message ",
                    "height": "stretch",
                    "id": "1",
                    "isRequired": true,
                    "label": "Hello this is label",
                    "type": "Input.Date",
                    "isVisible": false
                },
                {
                    "errorMessage": "error message error message error message error message ",
                    "height": "stretch",
                    "id": "3",
                    "isRequired": true,
                    "label": "This is label",
                    "type": "Input.Time",
                    "isVisible": false
                }
            ]
        },
        {
            "actions": [
                {
                    "targetElements": [
                        "1",
                        "3"
                    ],
                    "title": "Action.ToggleVisibility",
                    "type": "Action.ToggleVisibility"
                }
            ],
            "id": "2",
            "type": "ActionSet"
        }
    ],
    "minHeight": "400px",
    "type": "AdaptiveCard",
    "version": "1.3"
}
`

## How Verified
How you verified the fix, including one or all of the following: 
1. Ran BTP for height changes and BTP for toggle visibility

2022-11-28 08:49 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
> +    override func configureLayoutAndVisibility(element: NSObject, isRootMinHeightAvailable: Bool) {
```suggestion
    override func configureLayoutAndVisibility(element: ACSBaseCardElement, isRootMinHeightAvailable: Bool) {
```

2022-11-28 08:49 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRColumnSetView.swift
> +        self.setMinimumHeight((element as? ACSCollectionTypeElement)?.getMinHeight())
```suggestion
        self.setMinimumHeight(element.getMinHeight())
```

2022-11-28 08:50 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
> +    func configureLayoutAndVisibility(element: NSObject, isRootMinHeightAvailable: Bool)
```suggestion
    func configureLayoutAndVisibility(element: ACSBaseCardElement, isRootMinHeightAvailable: Bool)
```

2022-11-28 08:52 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
> +    func configureLayoutAndVisibility(element: NSObject, isRootMinHeightAvailable: Bool) {
```suggestion
    func configureLayoutAndVisibility(element: ACSBaseCardElement, isRootMinHeightAvailable: Bool) {
```

2022-11-28 08:57 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
> +    func visibilityManagerReactivateConstraint() {
```suggestion
    func visibilityManagerUpdateConstraint() {
```

2022-11-28 09:02 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRView.swift
> +            facadeArray.append(facade)
`visibilityManagerSetLastStretchableView(isHidden: isHide)` is depend on **isHide** variable.
can you please check?

2022-11-28 09:06 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
> +        XCTAssertEqual(columnView.arrangedSubviews.count, 4)
Why count is increase? if content at center then there is already two _stretchableViews_ are present, if i'm not wrong then why subviews count +1.

2022-11-28 09:07 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ColumnRendererTests.swift
> +        XCTAssertEqual(columnView.arrangedSubviews.count, 3)
Why count is increase? if content at center then there is already one _**stretchableView**_ is present, if i'm not wrong then why subviews count +1.

2022-11-28 10:00 UTC, urmitchauhan requested changes

2022-11-28 10:00 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCardsTests/Renderers/ContainerRendererTests.swift
> +        XCTAssertEqual(containerView.stackView.arrangedSubviews.capacity, 3)
Please add comment for stretchable views is hide when there is other stretchable views are present.

2022-11-28 10:00 UTC, urmitchauhan commented on source/macos/AdaptiveCards/AdaptiveCards/Views/ACRContentStackView.swift
> +        }
can we move this `isBackgroundImageAvailable` at caller function. so we can remove the whole element dependency from this methods?
you can create tuple that can have necessary card properties.

```
typealias ACSElementProperties = (verticalContentAlignment: ACSVerticalContentAlignment, minHeight: NSNumber?, heightType: ACSHeightType, type: ACSCardElementType, isBackgroundImageAvailable: Bool)
```

```
func configureLayoutAndVisibility(elementProperties: ACSElementProperties, isRootMinHeightAvailable: Bool) {

}
```

2022-11-28 16:57 UTC, urmitchauhan approved these changes

2022-11-29 04:24 UTC, sidkotha approved these changes

2022-11-29 05:34 UTC, merged